name: Build CV
on:
  push:
    branches:
      - main
jobs:
  build_cv:
    name: Build CV 📬
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Compile CV
        uses: workflow/nix-shell-action@v3
        with:
          flakes-from-devshell: true
          script: typst compile main.typ

      - name: Push PDF to branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch
          git checkout pdf
          mv main.pdf cv.pdf
          git add cv.pdf
          git commit -m "Add generated PDF"
          git push -f "https://x-access-token:${{secrets.GH_TOKEN}}@github.com/redsuperbat/cv.git" pdf
